#-------------THE SCRIPT-------------

stack = []

arg1 = 5
arg2 = 10
arg3 = 1500
# demonstrate loops, if statments
# call with 3 command line arguments, all ints
stack.append(1)
i = stack.pop()
for _ in range(10):
    stack.append(i)
    stack.append(arg1)
    b = stack.pop()
    a = stack.pop()
    stack.append(a > b)
    if stack.pop():
        stack.append('*')
        stack.append(i)
        b = stack.pop()
        a = stack.pop()
        stack.append(a * b)
        print(stack[-1])
        stack.pop()
    stack.append(i)
    stack.append(arg1)
    b = stack.pop()
    a = stack.pop()
    stack.append(a == b)
    if stack.pop():
        stack.append('*')
        stack.append(i)
        b = stack.pop()
        a = stack.pop()
        stack.append(a * b)
        print(stack[-1])
        stack.pop()
    stack.append(i)
    stack.append(1)
    b = stack.pop()
    a = stack.pop()
    stack.append(a + b)
    i = stack.pop()
stack.append(0)
sum_of_multiples = stack.pop()
stack.append(1)
multiple_by_factor = stack.pop()
for _ in range(1500):
    stack.append(arg1)
    stack.append(multiple_by_factor)
    b = stack.pop()
    a = stack.pop()
    stack.append(a * b)
    arg1currentmultiple = stack.pop()
    stack.append(arg1currentmultiple)
    stack.append(arg3)
    b = stack.pop()
    a = stack.pop()
    stack.append(a < b)
    if stack.pop():
        stack.append(sum_of_multiples)
        stack.append(arg1currentmultiple)
        b = stack.pop()
        a = stack.pop()
        stack.append(a + b)
        sum_of_multiples = stack.pop()
    stack.append(arg2)
    stack.append(multiple_by_factor)
    b = stack.pop()
    a = stack.pop()
    stack.append(a * b)
    arg2currentmultiple = stack.pop()
    stack.append(arg2currentmultiple)
    stack.append(arg3)
    b = stack.pop()
    a = stack.pop()
    stack.append(a < b)
    if stack.pop():
        stack.append(sum_of_multiples)
        stack.append(arg2currentmultiple)
        b = stack.pop()
        a = stack.pop()
        stack.append(a + b)
        sum_of_multiples = stack.pop()
    stack.append(1)
    stack.append(multiple_by_factor)
    b = stack.pop()
    a = stack.pop()
    stack.append(a + b)
    multiple_by_factor = stack.pop()
print(sum_of_multiples)
