stack = []

print(stack[-1])
stack.append(7)
print(stack[-1])
stack.append('string')
print(stack[-1])
stack.pop()
print(stack[-1])
stack.pop()
print(stack[-1])
stack.append(True)
print(stack[-1])
stack.append(False)
print(stack[-1])
stack.pop()
print(stack[-1])
stack.pop()
print(stack[-1])
stack.append(100)
x = stack.pop()
print(stack[-1])
print(x)
stack.append(x)
print(stack[-1])
stack.pop()
print(stack[-1])
stack.append(7)
stack.append(5)
b = stack.pop()
a = stack.pop()
stack.append(a + b)
print(stack[-1])
stack.append(6)
b = stack.pop()
a = stack.pop()
stack.append(a - b)
print(stack[-1])
stack.append(2)
b = stack.pop()
a = stack.pop()
stack.append(a * b)
print(stack[-1])
stack.append(6)
b = stack.pop()
a = stack.pop()
stack.append(a / b)
print(stack[-1])
stack.pop()
stack.append(20)
stack.append(8)
b = stack.pop()
a = stack.pop()
stack.append(a % b)
print(stack[-1])
stack.pop()
stack.append(7)
stack.append(8)
b = stack.pop()
a = stack.pop()
stack.append(a < b)
print(stack[-1])
if stack.pop():
    stack.append(7)
    print(stack[-1])
stack.append(6)
b = stack.pop()
a = stack.pop()
stack.append(a > b)
print(stack[-1])
stack.pop()
print(stack[-1])
stack.append(7)
stack.append(8)
b = stack.pop()
a = stack.pop()
stack.append(a == b)
print(stack[-1])
stack.pop()
stack.append(7)
stack.append(7)
b = stack.pop()
a = stack.pop()
stack.append(a == b)
print(stack[-1])
stack.pop()
stack.append(True)
print(stack[-1])
a = stack.pop()
stack.append(not a)
print(stack[-1])
stack.pop()
print(stack[-1])
print(x)
for _ in range(10):
    for _ in range(10):
        stack.append(1)
        stack.append(x)
        b = stack.pop()
        a = stack.pop()
        stack.append(a + b)
        x = stack.pop()
        print(x)
# comment this is my code