stack = []

stack.append(7)
stack.append(7)
b = stack.pop()
a = stack.pop()
stack.append(a == b)
print(stack[-1])
stack.pop()
stack.append(True)
print(stack[-1])
a = stack.pop()
stack.append(not a)
print(stack[-1])
stack.append(True)
print(stack[-1])
a = stack.pop()
b = stack.pop()
stack.append(a and b)
print(stack[-1])
stack.pop()
stack.append(True)
stack.append(False)
print(stack[-1])
a = stack.pop()
b = stack.pop()
stack.append(a or b)
print(stack[-1])
stack.pop()
stack.append(1)
x = stack.pop()
for _ in range(25):
    for _ in range(25):
        stack.append(x)
        stack.append(1)
        b = stack.pop()
        a = stack.pop()
        stack.append(a + b)
        x = stack.pop()
        print(x)